[project]
name = "math-worksheet-generator"
version = "0.1.2"
description = "Math Worksheet Generator for Kids"
readme = "README.md"
authors = [
    {name = "abakhru", email = "bakhru@me.com"},
]
license = {text = "MIT"}
requires-python = ">=3.14"
dependencies = [
    "rich",
    "click",
    "arrow",
    "numpy",
    "weasyprint",
]


[dependency-groups]
dev = [
    "pytest",
    "ruff",
]
